### ISSUE TITLE
the filter script for lines and symbols "implies" a lua interpreter called "lua" in the system

### ISSUE THREAD

**Issue by eko234** [gustavo-hms/peneira#10]
Hi Gustavo, hope you doing well, today while reinstalling some stuff for my setup, I realized that the script I mention wont work if "lua" is not installed in the system, the thing is I have luajit (I know that strictly speaking it is not lua), but I naively got the impression that setting the lua_interpreter option should have worked, luckily I'm enjoying peneira once again, but also think it would be good to note this dependency, I know it's kinda an "obvious" dependency, but I got the impression it is due to an implementation detail more than a core issue, as luar indeed works as expected setting the interpreter option.

Thanks for your work again, have a nice one! :)

**Comment by gustavo-hms** [comment]
Again, sorry for the late reply. I promisse I'll manage to work on these tasks more frequently. You users deserve that.

It's funny that I noticed the same issue some weeks before you when I reinstalled the OS on my machine. For that problem, I think I have an easy solution. Hopefully, I'm gonna work on it this weekend.

Thank you for helping me with that.

**Comment by gustavo-hms** [comment]
Hi, @eko234 ! Could you confirm #11 solved this problem for you?

Thanks in advance.

**Comment by eko234** [comment]
Yes it does, thanks!
