### ISSUE TITLE
"%s" like strings cause conflicts when searching

### ISSUE THREAD

**Issue by eko234** [gustavo-hms/peneira#12]
Hi Gustavo, hope you are doing well, the other day I was making some nice filters with peneira, and while testing a grep like filter on my plugins folder I noticed it failed when I pressed a single key, upon further inspection seems like when peneira finds a "%s" it freaks out, turns out the file causing that issue was `luar.lua` I guess it should be something to do with expansions, also related to that file indeed.

**Comment by gustavo-hms** [comment]
Hi, @eko234! Nice to hear you are writing custom filters using `peneira`. It's something I hope others do as well to build, in the long run, a library of filters like the venerable `unite` plugin for vim.

Could you please give me a small example to reproduce the bug? I've tried the following but couldn't reproduce the issue:

```kak
peneira 'teste: ' %{ printf "um\ndois\n%s\nquatro" três } %{ echo %arg{1} }
```

The above excerpt works flawlessly.

**Comment by gustavo-hms** [comment]
By the way, a `grep` filter is something I'm interested too. Would you be interested in making a PR to implement that filter here? I could help you implementing it, including adding highlighters.

Or, alternatively, could you make your implementation public, in a way I can contribute to?

**Comment by eko234** [comment]
> By the way, a `grep` filter is something I'm interested too. Would you be interested in making a PR to implement that filter here? I could help you implementing it, including adding highlighters.
> 
> Or, alternatively, could you make your implementation public, in a way I can contribute to?

Sure, I could make a PR sharing what I have right now, it is not very polished but if you can improve upon it it would be great!

**Comment by eko234** [comment]
> ```kakscript
> peneira 'teste: ' %{ printf "um\ndois\n%s\nquatro" três } %{ echo %arg{1} }
> ```

You are right, I narrowed it even further and found this string causes problems "☾%s" it is used in luar.lua, maybe something gets messed up with the representation of that character.

**Comment by gustavo-hms** [comment]
Could you please give me a minimal code snippet that reproduces this bug?

**Comment by eko234** [comment]
> Could you please give me a minimal code snippet that reproduces this bug?

sure, `peneira 'teste: ' %{ printf "um\ndois\n%s\nquatro" ☾%s } %{ echo %arg{1} }`

**Comment by gustavo-hms** [comment]
Although it's true that the above code snippet does fire the problem, it doesn't seem for me to be a realistic scenario. Did you really used a unicode moon on any of your `kak` scripts?

I mean, I chose a `☾` to use as string delimiter exactly because I thought no one would use it.. 😅

**Comment by eko234** [comment]
Ah, sure, hahaha, totally get you, I landed on this trying to hack something in the peneira source using peneira, but it's not a deal breaker, still using it over fzf to this day <4
