### ISSUE TITLE
Pressing enter when no matches let's the buffer in a broken state

### ISSUE THREAD

**Issue by eko234** [gustavo-hms/peneira#14]
Hi, I've noticed the reason for a bug that's been bugging me :v , seems like pressing enter when there are no matches let's the buffer in an illegal state, I guess it could be fixed it worked around forcing the closing of the buffer on any kind of exit.

**Comment by eko234** [comment]
I patched my local peneira copy, wrapping the line 113 in peneira.kak with a try statement, it works for me, but when doing file search it creates a file "" if no matches occur, but at least it doesnt lets the buffer in a weird state, maybe doing some error handling there could be a good solution.

**Comment by eko234** [comment]
``` kakscript
            try %{
              execute-keys %opt{peneira_selected_line}gx_\"xy
            } catch %{
              peneira-clear-environment
              fail "bruh..."
            }

```

**Comment by gustavo-hms** [comment]
Hmmm... You are right! I've never noticed that.

I think I can implement a more robust solution. But I'll need some time to do that.

**Comment by gustavo-hms** [comment]
@eko234 , could you please test the fix made in the `fix-broken-state` branch to see if this bug was really fixed?

Thanks!

**Comment by eko234** [comment]
Hello, I'll gladly do
