### ISSUE TITLE
Is async possible?

### ISSUE THREAD

**Issue by eko234** [gustavo-hms/peneira#15]
Hi, I was wondering if it would be possible to make the process of buffer population asyc? afik It could make the initial load feel "faster"
but in the end the filtering would be the same right?

**Comment by gustavo-hms** [comment]
This would be a very nice feature. But I'm afraid it would make the plugin much more complex.

I'll keep this issue open for now while I see if I can think a way to implement it without increasing the complexity of the plugin to much.
