### ISSUE TITLE
id error: number-lines

### ISSUE THREAD

**Issue by sdothum** [gustavo-hms/peneira#18]
With kakoune v2024.05.08 peneira fails on "remove-highlighter window/number-lines".

Commenting this line out in peneira.kak appears to solve the problem (for buffer picking). Not sure if this is actually a "good fix" or potentially a problem for other peneira use cases.

**Comment by gustavo-hms** [comment]
Hi, Steven! Thanks for reporting this bug.

I'm using `v2024.05.18` but couldn't reproduce the bug. Nevertheless, I still have a suspect: please check [this section](https://github.com/gustavo-hms/peneira#caveats) on `README` to see if that can fix your problem. If it doesn't, then please tell me and I'll investigate it further.

**Comment by sdothum** [comment]
Hello Gustavo,

Thanks for the link. Never thought to reread the project page after having not had any issues with peneira for so long. My apologies.

The first example solved my reported issue. Closing this issue. 

Much thanks again.

**Comment by losnappas** [comment]
I don't use a number-lines highlighter, and I also run into this issue. I can work around it like,

```
hook global WinCreate .* %{ addhl window/number-lines regex __ 0:default }
```

but seems a bit strange. I think for my case removing/try-catching it makes sense?

**Comment by losnappas** [comment]
Removing an "unknown" highlighter became an error here https://github.com/mawww/kakoune/commit/b1c114bf6d950684df0524e450782a151e6a0323 , on April 12 2024.

Wrapping it in `try` restores the behavior this plugin used to have, so I'll make a pr for that and let you judge from there.
